In [2]:
import os
os.listdir()

['.ipynb_checkpoints',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Untitled.ipynb']

In [3]:
import pandas
df = pandas.read_csv("supermarkets.csv")

In [4]:
df


ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [6]:
json.set_index("ID")

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [7]:
print(df,json
     )

   ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20      ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995

In [8]:
print(json
     )

   ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20  


In [9]:
json df


SyntaxError: invalid syntax (<ipython-input-9-0d8ed8d5dad6>, line 1)

In [10]:
json,df

(   ID          Address           City             State Country         Name  \
 0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
 1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
 2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
 3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
 4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
 5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   
 
    Employees  
 0          8  
 1         15  
 2         25  
 3         10  
 4         12  
 5         20  ,
    ID          Address           City             State Country         Name  \
 0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
 1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
 2   3      332 Hill St  San Francisco  California 94114     USA  Super Riv

In [2]:
df


NameError: name 'df' is not defined

# Reding the XLSX files



In [3]:
df


NameError: name 'df' is not defined

In [4]:
json

NameError: name 'json' is not defined

In [6]:
json = pandas.read_csv("supermarkets.csv")

NameError: name 'pandas' is not defined

In [ ]:
import pandas


In [7]:
xll = pandas.read_excel("supermarkets.xlsx")
xll

NameError: name 'pandas' is not defined

In [8]:
import pandas


In [11]:
xll = pandas.read_excel("supermarkets.xlsx")
xll

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [16]:
xlld


NameError: name 'xlld' is not defined

In [17]:
xll2=xll.set_index("ID")


In [18]:
xll2


Address           City             State Country Supermarket Name  \
ID                                                                              
1      3666 21st St  San Francisco          CA 94114     USA          Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA      Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA      Super River   
4      3995 23rd St  San Francisco          CA 94114     USA       Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA          Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA       Richvalley   

    Number of Employees  
ID                       
1                     8  
2                    15  
3                    25  
4                    10  
5                    12  
6                    20

In [19]:
xll = pandas.read_excel("supermarkets.xlsx", header=None)
xll

0                1              2                 3        4  \
0  ID          Address           City             State  Country   
1   1     3666 21st St  San Francisco          CA 94114      USA   
2   2   735 Dolores St  San Francisco          CA 94119      USA   
3   3      332 Hill St  San Francisco  California 94114      USA   
4   4     3995 23rd St  San Francisco          CA 94114      USA   
5   5  1056 Sanchez St  San Francisco        California      USA   
6   6  551 Alvarado St  San Francisco          CA 94114      USA   

                  5                    6  
0  Supermarket Name  Number of Employees  
1           Madeira                    8  
2       Bready Shop                   15  
3       Super River                   25  
4        Ben's Shop                   10  
5           Sanchez                   12  
6        Richvalley                   20

In [20]:
xll = pandas.read_excel("supermarkets.xlsx")
xll

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [23]:
xll.columns=["vada","IDli","Adda","Nagar","Rajya","Mall ka naaam","Number bata"]


In [24]:
xll


vada             IDli           Adda             Nagar Rajya Mall ka naaam  \
0     1     3666 21st St  San Francisco          CA 94114   USA       Madeira   
1     2   735 Dolores St  San Francisco          CA 94119   USA   Bready Shop   
2     3      332 Hill St  San Francisco  California 94114   USA   Super River   
3     4     3995 23rd St  San Francisco          CA 94114   USA    Ben's Shop   
4     5  1056 Sanchez St  San Francisco        California   USA       Sanchez   
5     6  551 Alvarado St  San Francisco          CA 94114   USA    Richvalley   

   Number bata  
0            8  
1           15  
2           25  
3           10  
4           12  
5           20

In [29]:
xll.set_index("vada",inplace=True ,drop=False)

In [30]:
xll

vada             IDli           Adda             Nagar Rajya  \
vada                                                                 
1        1     3666 21st St  San Francisco          CA 94114   USA   
2        2   735 Dolores St  San Francisco          CA 94119   USA   
3        3      332 Hill St  San Francisco  California 94114   USA   
4        4     3995 23rd St  San Francisco          CA 94114   USA   
5        5  1056 Sanchez St  San Francisco        California   USA   
6        6  551 Alvarado St  San Francisco          CA 94114   USA   

     Mall ka naaam  Number bata  
vada                             
1          Madeira            8  
2      Bready Shop           15  
3      Super River           25  
4       Ben's Shop           10  
5          Sanchez           12  
6       Richvalley           20

In [1]:
import numpy


In [2]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [12]:
n = numpy.arange(27,207,5)
n

array([ 27,  32,  37,  42,  47,  52,  57,  62,  67,  72,  77,  82,  87,
        92,  97, 102, 107, 112, 117, 122, 127, 132, 137, 142, 147, 152,
       157, 162, 167, 172, 177, 182, 187, 192, 197, 202])

In [10]:
help(numpy.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [16]:
n.reshape(6,6)

array([[ 27,  32,  37,  42,  47,  52],
       [ 57,  62,  67,  72,  77,  82],
       [ 87,  92,  97, 102, 107, 112],
       [117, 122, 127, 132, 137, 142],
       [147, 152, 157, 162, 167, 172],
       [177, 182, 187, 192, 197, 202]])

In [19]:
import cv2

In [22]:
img = cv2.imread("smallgray.png",1)

In [23]:
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

img


In [29]:
new=img.reshape(9,5)

In [31]:
new


array([[187, 187, 187, 158, 158],
       [158, 104, 104, 104, 121],
       [121, 121, 143, 143, 143],
       [198, 198, 198, 125, 125],
       [125, 255, 255, 255, 255],
       [255, 255, 147, 147, 147],
       [209, 209, 209, 134, 134],
       [134, 255, 255, 255,  97],
       [ 97,  97, 182, 182, 182]], dtype=uint8)

In [32]:
cv2.imwrite("Newimg.png",new)

True

In [44]:
aimg = cv2.imread("test.jpg",1)
aimg

array([[[36, 31, 28],
        [36, 31, 28],
        [36, 31, 28],
        ...,
        [36, 31, 28],
        [36, 31, 28],
        [36, 31, 28]],

       [[36, 31, 28],
        [36, 31, 28],
        [36, 31, 28],
        ...,
        [36, 31, 28],
        [36, 31, 28],
        [36, 31, 28]],

       [[36, 31, 28],
        [36, 31, 28],
        [36, 31, 28],
        ...,
        [36, 31, 28],
        [36, 31, 28],
        [36, 31, 28]],

       ...,

       [[36, 31, 28],
        [36, 31, 28],
        [36, 31, 28],
        ...,
        [36, 31, 28],
        [36, 31, 28],
        [36, 31, 28]],

       [[36, 31, 28],
        [36, 31, 28],
        [36, 31, 28],
        ...,
        [36, 31, 28],
        [36, 31, 28],
        [36, 31, 28]],

       [[36, 31, 28],
        [36, 31, 28],
        [36, 31, 28],
        ...,
        [36, 31, 28],
        [36, 31, 28],
        [36, 31, 28]]], dtype=uint8)

In [34]:
aimg


array([[31, 31, 31, ..., 31, 31, 31],
       [31, 31, 31, ..., 31, 31, 31],
       [31, 31, 31, ..., 31, 31, 31],
       ...,
       [31, 31, 31, ..., 31, 31, 31],
       [31, 31, 31, ..., 31, 31, 31],
       [31, 31, 31, ..., 31, 31, 31]], dtype=uint8)

In [35]:
print(aimg)

[[31 31 31 ... 31 31 31]
 [31 31 31 ... 31 31 31]
 [31 31 31 ... 31 31 31]
 ...
 [31 31 31 ... 31 31 31]
 [31 31 31 ... 31 31 31]
 [31 31 31 ... 31 31 31]]


In [43]:
aimg.reshape(80,30,80)

ValueError: cannot reshape array of size 273498 into shape (80,30,80)

In [51]:
name = numpy.roll(aimg,1, axis=0)

In [53]:
cv2.imwrite("lo2l.png",name)

True

In [55]:
import folium


In [58]:
map = folium.Map(location=[50,90])
map

In [59]:
map.save("map1.html")